<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net45</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PoKGameDir>C:\Program Files (x86)\Steam\steamapps\common\The road of Jianghu\daojianjianghulu_Data\Managed\Translators\</PoKGameDir>
		<Xyzj2GameDir>G:\SteamLibrary\steamapps\common\下一站江湖Ⅱ\下一站江湖Ⅱ\下一站江湖Ⅱ_Data\Managed\Translators</Xyzj2GameDir>
		<LoMGameDir>C:\Program Files (x86)\Steam\steamapps\common\LegendOfMortal\Mortal_Data\Managed\Translators</LoMGameDir>
		<BaseFolder>\..\..\..\</BaseFolder>
		<DeployToGameDirs>false</DeployToGameDirs>
		<Configurations>Debug;Release</Configurations>
		<UserSecretsId>f11951a3-bacd-43f2-a9fa-0187cf947674</UserSecretsId>
	</PropertyGroup>
	
	<ItemGroup>
		<Reference Include="XUnity.AutoTranslator.Plugin.Core">
			<HintPath>..\libs\XUnity.AutoTranslator.Plugin.Core.dll</HintPath>
		</Reference>
		<Reference Include="XUnity.AutoTranslator.Plugin.ExtProtocol">
			<HintPath>..\libs\XUnity.AutoTranslator.Plugin.ExtProtocol.dll</HintPath>
		</Reference>
		<Reference Include="XUnity.Common">
			<HintPath>..\libs\XUnity.Common.dll</HintPath>
		</Reference>
	</ItemGroup>
 
	<ItemGroup>
		<PackageReference Include="YamlDotNet" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.45" PrivateAssets="All" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="ILRepacker" Condition="$(Configuration) == 'Release'">
		<PropertyGroup>
			<ReleaseFolder>$(MSBuildThisFileDirectory)..\Release\</ReleaseFolder>
			<ReleaseTranslatorsFolder>$(ReleaseFolder)Translators\</ReleaseTranslatorsFolder>
			<ReleaseSampleConfigFolder>$(ReleaseFolder)SampleConfig\</ReleaseSampleConfigFolder>
		</PropertyGroup>

		<ItemGroup>
			<SampleConfigFiles Include="$(MSBuildThisFileDirectory)SampleConfig\**\*" />
		</ItemGroup>

		<MakeDir Directories="$(ReleaseTranslatorsFolder);$(ReleaseSampleConfigFolder)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ReleaseTranslatorsFolder)" />
		<Copy SourceFiles="@(SampleConfigFiles)" DestinationFiles="@(SampleConfigFiles->'$(ReleaseSampleConfigFolder)%(RecursiveDir)%(Filename)%(Extension)')" />

		<MakeDir Directories="$(PoKGameDir);$(Xyzj2GameDir);$(LoMGameDir)" Condition="'$(DeployToGameDirs)' == 'true'" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PoKGameDir)" Condition="'$(DeployToGameDirs)' == 'true'" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Xyzj2GameDir)" Condition="'$(DeployToGameDirs)' == 'true'" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(LoMGameDir)" Condition="'$(DeployToGameDirs)' == 'true'" />
	</Target>

</Project>
